/**
 * Content Engine — Gemini Image Generation
 * Generates hero images via Google Gemini REST API (gemini-3-pro-image-preview).
 *
 * Image prompts are generated by Claude Haiku using the article title + H2 outline,
 * so each image is visually specific to the article subject rather than generic.
 */

import { writeFileSync } from 'fs';
import { env, GEMINI_MODEL, MODEL_ALT } from './config.js';
import { callModel } from './openrouter.js';

const BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/models';

/**
 * Generate an image and save to disk.
 */
export async function generateImage(prompt, outputPath, aspectRatio = '16:9') {
  if (!env.GEMINI_API_KEY) {
    console.log('  GEMINI_API_KEY not set — skipping image generation');
    return false;
  }

  const url = `${BASE_URL}/${GEMINI_MODEL}:generateContent?key=${env.GEMINI_API_KEY}`;
  const body = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: {
      responseModalities: ['IMAGE', 'TEXT'],
      imageConfig: { aspectRatio },
    },
  };

  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      if (!res.ok) {
        const err = await res.text();
        console.log(`  Gemini error (${res.status}): ${err}`);
        if (attempt < 1) { await sleep(5000); continue; }
        return false;
      }

      const data = await res.json();
      const parts = data.candidates?.[0]?.content?.parts || [];

      for (const part of parts) {
        if (part.inlineData?.mimeType?.startsWith('image/')) {
          const imageBuffer = Buffer.from(part.inlineData.data, 'base64');
          writeFileSync(outputPath, imageBuffer);
          console.log(`  Image saved: ${outputPath} (${Math.round(imageBuffer.length / 1024)}KB)`);
          return true;
        }
      }

      console.log('  No image data in Gemini response');
      if (attempt < 1) { await sleep(5000); continue; }
    } catch (err) {
      console.log(`  Gemini error: ${err.message}`);
      if (attempt < 1) { await sleep(5000); continue; }
    }
  }

  return false;
}

/**
 * Generate a hero image for an article.
 * Uses Claude Haiku to write a specific visual prompt from the article title + outline.
 * Falls back to static keyword lookup if Haiku call fails.
 */
export async function generateHeroImage(slug, title, topic, outputDir, h2Outline = []) {
  console.log(`  Generating image prompt for "${title}"...`);

  let prompt;
  try {
    prompt = await buildHeroPromptAI(title, topic, h2Outline);
    console.log(`  AI prompt: ${prompt.slice(0, 120)}...`);
  } catch (err) {
    console.log(`  AI prompt failed (${err.message}), using static fallback`);
    prompt = buildHeroPromptStatic(title, topic);
  }

  const outputPath = `${outputDir}/${slug}.jpg`;
  const ok = await generateImage(prompt, outputPath, '16:9');
  if (!ok) return null;

  const altText = buildAltText(title, topic);
  return { path: outputPath, altText };
}

// ── AI Prompt Generation ───────────────────────────────────────────────────────

/**
 * Ask Claude Haiku to write a specific, article-aware image prompt.
 * Uses title + H2 outline to understand what the article is actually about.
 */
async function buildHeroPromptAI(title, topic, h2Outline) {
  const outlineText = h2Outline.length > 0
    ? h2Outline.slice(0, 4).join('\n- ')
    : topic;

  const system = `You write image generation prompts for a destination wedding website. Your prompts produce editorial-quality photographs that are visually specific to the article subject. You never produce generic beach-ceremony shots unless the article is literally about beach ceremonies.`;

  const user = `Write a Gemini image generation prompt for the hero image of this article.

Article title: "${title}"
Article sections cover:
- ${outlineText}

Rules:
- The image must be VISUALLY SPECIFIC to the article subject. If it's about wedding cakes, show cakes. If it's about shoes, show shoes. If it's about budget planning, show a planning/flat-lay scene. If it's about a specific destination, show that destination.
- Never default to a generic beach ceremony shot unless the article is specifically about beach ceremonies.
- Style: editorial photography, natural light, warm tones, aspirational but not stock-photo. No text, no logos, no watermarks.
- Length: 1-3 sentences maximum. Be concrete and visual, not abstract.
- Do NOT include the word "prompt" or meta-commentary. Just the image description.`;

  const { text } = await callModel(MODEL_ALT, system, user, { temperature: 0.7, max_tokens: 200 });
  const prompt = text.trim().replace(/^["']|["']$/g, '');

  if (!prompt || prompt.length < 20) throw new Error('Empty prompt returned');
  return prompt;
}

// ── Static Fallback ────────────────────────────────────────────────────────────

/**
 * Rule-based fallback using article title keywords.
 * More specific than the old topic-only lookup — checks title first.
 */
function buildHeroPromptStatic(title, topic) {
  const t = (title + ' ' + topic).toLowerCase();

  // Food & drink
  if (/\bcake[s]?\b/.test(t)) return 'A stunning tiered wedding cake decorated with tropical flowers and seashells, soft diffused light, styled on a driftwood table with ocean blurred in background. Editorial food photography, warm tones.';
  if (/punch|drink[s]?|cocktail|beverage/.test(t)) return 'A beautiful tropical wedding drink display — glass dispensers with colorful fruit punches and fresh garnishes, arranged on a draped table with beach flowers and greenery. Soft natural light, editorial style.';
  if (/\bmenu\b|catering|food|seafood/.test(t)) return 'An elegantly styled beach wedding reception table with tropical food spreads — fresh seafood, colorful salads, artisan bread — warm candlelight and floral centerpieces, ocean view backdrop. Editorial photography.';
  if (/dessert|favor[s]?|edible/.test(t)) return 'A styled beach wedding dessert display — petit fours, truffles, and tropical sweets arranged on tiered stands with seashells and coral, warm ambient light, dreamy depth of field. Editorial photography.';
  if (/bridal shower|bachelorette/.test(t)) return 'A chic tropical bridal shower table setting — pastel flowers, champagne flutes, macarons and tropical fruits arranged beautifully, bright airy natural light. Editorial flat-lay style.';

  // Decor & styling
  if (/centerpiece[s]?/.test(t)) return 'A close-up of a stunning beach wedding centerpiece — white orchids, driftwood, and tropical greenery in a glass vessel, soft bokeh background with ocean light filtering through. Editorial photography.';
  if (/flower[s]?|floral|bouquet[s]?/.test(t)) return 'A lush tropical wedding bouquet of white plumerias, birds of paradise, and trailing greenery held by a bride, warm golden light, ocean softly blurred in background. Editorial photography.';
  if (/color[s]?|colour[s]?|color scheme/.test(t)) return 'A beautifully composed wedding color palette flat lay — fabric swatches in soft teal, blush, and gold alongside tropical flowers, ribbon, and stationery on a white marble surface. Editorial styling photography.';
  if (/decoration[s]?|decor/.test(t)) return 'A beautifully decorated beach wedding reception space — draped white fabric, lanterns glowing at dusk, tropical floral arrangements on tables, soft bokeh lights in the background. Editorial photography.';
  if (/lighting|evening|night/.test(t)) return 'A magical beach wedding at twilight — lanterns and string lights reflected on wet sand, silhouettes of guests at candlelit tables, a warm amber glow over the ocean. Editorial photography.';
  if (/table|tabletop/.test(t)) return 'A styled beach wedding tablescape overhead shot — white linen, tropical leaf place settings, seashell details, and a low floral runner, warm soft light. Editorial flat-lay photography.';
  if (/vase[s]?|sea glass/.test(t)) return 'A collection of handmade sea glass vases in pale aqua and frosted white holding delicate white flowers, arranged on weathered driftwood with soft coastal light. Artisan craft photography.';

  // Attire & accessories
  if (/shoe[s]?|heel[s]?|sandal[s]?/.test(t)) return 'Close-up of elegant bridal sandals on a sun-warmed wooden deck, pale toes in the sand nearby, soft ocean light and floral petals scattered. Editorial detail photography.';
  if (/dress|gown|look[s]?|style[s]?/.test(t)) return 'A bride in a flowing light chiffon gown standing at the edge of a sun-bright beach, the fabric catching a gentle sea breeze, warm horizon light. Editorial fashion photography.';
  if (/accessor/.test(t)) return 'A styled flat lay of elegant beach bridal accessories — delicate pearl earrings, a dainty necklace, a hair comb with tiny shells — arranged on ivory linen with rose petals. Editorial detail photography.';
  if (/nail[s]?/.test(t)) return 'Close-up of a bride\'s beautifully manicured hands holding a small tropical flower, soft-focus beach in the background, warm golden light. Editorial beauty photography.';
  if (/bridesmaid[s]?/.test(t)) return 'Three bridesmaids in flowing ocean-blue dresses standing barefoot on the beach at golden hour, laughing together, warm sunset light behind them. Editorial photography.';

  // Planning & logistics
  if (/checklist|timeline|planning/.test(t)) return 'An overhead flat lay of a beautifully designed wedding planning notebook, a pen, a small bouquet of flowers, and a coffee cup on a white linen surface, warm natural light. Editorial lifestyle photography.';
  if (/cost|budget|price|save money|afford/.test(t)) return 'A bright, styled overhead shot of a wedding budget worksheet with a cup of coffee, a small succulent, and a gold pen on a marble surface — aspirational planning aesthetic. Editorial photography.';
  if (/transportation|getting there|travel/.test(t)) return 'A couple sitting close together in a vintage convertible decorated with white ribbons and tropical flowers, smiling, palm trees and blue sky behind them. Editorial photography.';
  if (/tips?|guide|how to|advice/.test(t)) return 'A couple sitting together at a sunlit outdoor café table with a wedding planning book, laughing, tropical flowers and ocean visible in background. Editorial lifestyle photography.';
  if (/shoe valet|flip flop/.test(t)) return 'A charming beach wedding shoe valet station — a wooden crate filled with colorful flip flops, a chalkboard sign, and string lights, set up at the edge of a sandy aisle. Editorial photography.';

  // Specific destinations
  if (/cancun/.test(t)) return 'A romantic beachfront wedding setup in Cancun — turquoise Caribbean water, white sand, tropical flowers, elegant resort terrace. Late afternoon sun. Editorial photography.';
  if (/bali/.test(t)) return 'A dreamy Bali wedding ceremony in a lush jungle temple setting, stone carvings draped in white orchids, soft diffused tropical light through the forest canopy. Editorial photography.';
  if (/santorini/.test(t)) return 'A couple on a Santorini caldera-view terrace, iconic white and blue architecture, Aegean sunset in gold and amber, rose petals on white stone. Editorial photography.';
  if (/hawaii/.test(t)) return 'A Hawaiian beachfront ceremony with a floral lei arch, volcanic mountains in the background, barefoot in white sand, warm Pacific light. Editorial photography.';
  if (/jamaica/.test(t)) return 'A lush Jamaica resort wedding at sunset, tropical flowers in deep jewel tones, white gazebo on manicured lawn overlooking the turquoise sea. Editorial photography.';
  if (/punta cana/.test(t)) return 'An all-inclusive resort wedding in Punta Cana — palm-lined ceremony aisle, white fabric draping, Caribbean Sea shimmering behind. Editorial photography.';
  if (/tulum/.test(t)) return 'A bohemian Tulum jungle wedding — wooden altar wrapped in macramé and tropical greenery, cenote nearby, dappled light through ancient trees. Editorial photography.';
  if (/costa rica/.test(t)) return 'A Costa Rica eco-resort wedding on a canopy deck, tropical rainforest and misty mountains behind, bird of paradise florals. Editorial photography.';
  if (/key west/.test(t)) return 'A charming Key West wedding on a sun-drenched dock, sailboats visible in the background, white conch shell details, warm amber afternoon light. Editorial photography.';
  if (/palm beach/.test(t)) return 'An elegant Palm Beach wedding ceremony on a manicured oceanfront lawn, white orchids and palm fronds, a pristine Florida coastline in the background. Editorial photography.';

  // Specific article types
  if (/honeymoon/.test(t)) return 'A couple toasting on an overwater bungalow deck at sunset, turquoise lagoon surrounding them, champagne glasses catching the golden light. Editorial photography.';
  if (/celebrity/.test(t)) return 'A glamorous beachfront wedding reception setting — long table draped in white linen, crystal chandeliers hanging from palm trees, candles and white roses everywhere. Editorial photography.';
  if (/proposal|engagement/.test(t)) return 'A man on one knee proposing to his partner on a secluded beach at golden hour, ocean behind them, ring box open, her hands over her mouth in surprise. Cinematic photography.';
  if (/pros.*cons|consider/.test(t)) return 'A couple sitting side by side on a beach at sunset, reviewing something on a tablet together, laughing, the ocean calm behind them. Editorial lifestyle photography.';
  if (/indoor|inside|reception/.test(t)) return 'An elegantly decorated indoor beach-themed wedding reception — driftwood centerpieces, hanging lanterns, blue and white linens, soft warm lighting throughout the venue. Editorial photography.';
  if (/real wedding[s]?/.test(t)) return 'A candid moment from a real beach wedding — the couple laughing together just after the ceremony, confetti mid-air, ocean in the background, pure joy. Documentary wedding photography.';

  // Generic beach wedding fallback (last resort)
  return 'A couple exchanging vows on a sun-drenched tropical beach, soft golden hour light, white florals and driftwood arch, turquoise ocean in the distance. Editorial wedding photography, warm and cinematic.';
}

// ── Section Images ─────────────────────────────────────────────────────────────

/**
 * Generate contextual images for specific H2 sections of a visual-intent article.
 * Selects H2s evenly distributed across the article outline, generates one image
 * per selected section using a section-specific prompt from Claude Haiku.
 *
 * @param {string} slug - Article slug (used for filenames: slug-2.jpg, slug-3.jpg...)
 * @param {string} title - Article title (for context)
 * @param {string[]} h2Outline - Full H2 outline from the brief
 * @param {string} outputDir - Directory to write images to
 * @param {number} count - Number of section images to generate (2–4)
 * @returns {Array<{imageIndex, h2, path}>} Generated section image metadata
 */
export async function generateSectionImages(slug, title, h2Outline, outputDir, count) {
  if (!h2Outline?.length || count < 1) return [];

  // Select H2s evenly distributed across the outline (skip first and last —
  // those positions are awkward for inline images; keep the meaty middle)
  const usable = h2Outline.slice(1, -1).length > 0 ? h2Outline.slice(1, -1) : h2Outline;
  const step = Math.max(1, Math.floor(usable.length / count));
  const selectedH2s = Array.from({ length: count }, (_, i) => usable[Math.min(i * step, usable.length - 1)]).filter(Boolean);

  const results = [];
  for (let i = 0; i < selectedH2s.length; i++) {
    const h2 = selectedH2s[i];
    const imageIndex = i + 2; // hero is index 1, sections start at 2
    const outputPath = `${outputDir}/${slug}-${imageIndex}.jpg`;

    console.log(`  Generating section image ${imageIndex} for: "${h2}"`);
    let prompt;
    try {
      prompt = await buildSectionPromptAI(title, h2);
    } catch (err) {
      console.log(`    Section prompt failed (${err.message}), skipping`);
      continue;
    }

    const ok = await generateImage(prompt, outputPath, '16:9');
    if (ok) {
      results.push({ imageIndex, h2, path: outputPath, altText: h2 });
    } else {
      console.log(`    Section image ${imageIndex} failed — skipping`);
    }

    // Small pause between Gemini calls to avoid rate limiting
    if (i < selectedH2s.length - 1) await sleep(2000);
  }

  return results;
}

/**
 * Ask Claude Haiku to write a section-specific image prompt.
 * Uses the article title for context and the H2 heading as the primary subject.
 */
async function buildSectionPromptAI(articleTitle, h2Heading) {
  const system = `You write image generation prompts for a destination wedding website. Your prompts produce editorial-quality photographs that are visually specific to the exact subject described. Never produce generic beach ceremony shots.`;

  const user = `Write a Gemini image generation prompt for an inline section image.

Article: "${articleTitle}"
Section heading: "${h2Heading}"

Rules:
- The image must illustrate the SPECIFIC subject of the section heading, not the article in general.
- Style: editorial photography, natural light, warm tones, aspirational but not stock-photo. No text, no logos, no watermarks.
- If the heading describes a color palette, show a real styled scene (table, florals, fabric) in those exact colors.
- If it's a specific cake type, show that cake. Specific floral style — show those flowers. Specific destination — show that place.
- Length: 1-2 sentences. Concrete and visual only. Do NOT include the word "prompt" or any meta-commentary.`;

  const { text } = await callModel(MODEL_ALT, system, user, { temperature: 0.7, max_tokens: 150 });
  const prompt = text.trim().replace(/^["']|["']$/g, '');
  if (!prompt || prompt.length < 20) throw new Error('Empty prompt');
  return prompt;
}

function buildAltText(title, topic) {
  // Use title for specificity rather than generic topic
  const short = title.length > 80 ? title.slice(0, 77) + '...' : title;
  return short;
}

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}
